- [x] Import `lightscattering.svg` in `src/pages/prism.astro`.
- [x] Replace `prismCrystalSrc` with the new SVG in the HTML markup.
- [x] Update desktop CSS to let the SVG overflow to the right and place `.stats-right` (cards) above it with `z-index`.
- [x] Update `<960px` CSS to scale the SVG (`transform: scale(...) translate(...)`) so the prism is centralized and the tail is cleanly chopped off, keeping it stacked above the cards.
- [x] Ask User to verify the layout looks correct on both desktop and mobile.
